### PR TITLE
LLVM Integration test suite slides

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
thanks! can you add a link from the README?

**Comment by mstorsjo** [comment]
Looks like you missed the actual slides in the revised version of the commit?

**Comment by serge-sans-paille** [comment]
@mstorsjo that was a strategy to win the issue #42 :-)

**Comment by mstorsjo** [comment]
> @mstorsjo that was a strategy to win the issue #42 :-)

Lol - well played then! :P

**Pull request merged**
